/* Generated By:JavaCC: Do not edit this line. MIPSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MIPSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITE_SPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int SEMI = 3;
  /** RegularExpression Id. */
  int COLON = 4;
  /** RegularExpression Id. */
  int DOT = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int TIMES = 11;
  /** RegularExpression Id. */
  int BY = 12;
  /** RegularExpression Id. */
  int MOD = 13;
  /** RegularExpression Id. */
  int LSHIFT = 14;
  /** RegularExpression Id. */
  int RSHIFT = 15;
  /** RegularExpression Id. */
  int AMP = 16;
  /** RegularExpression Id. */
  int CARET = 17;
  /** RegularExpression Id. */
  int PIPE = 18;
  /** RegularExpression Id. */
  int TILDE = 19;
  /** RegularExpression Id. */
  int BANG = 20;
  /** RegularExpression Id. */
  int ABS = 21;
  /** RegularExpression Id. */
  int ADD = 22;
  /** RegularExpression Id. */
  int ADDCIU = 23;
  /** RegularExpression Id. */
  int ADDU = 24;
  /** RegularExpression Id. */
  int AND = 25;
  /** RegularExpression Id. */
  int B = 26;
  /** RegularExpression Id. */
  int BAL = 27;
  /** RegularExpression Id. */
  int BC0F = 28;
  /** RegularExpression Id. */
  int BC0FL = 29;
  /** RegularExpression Id. */
  int BC0T = 30;
  /** RegularExpression Id. */
  int BC0TLBC1F = 31;
  /** RegularExpression Id. */
  int BC1FL = 32;
  /** RegularExpression Id. */
  int BC1T = 33;
  /** RegularExpression Id. */
  int BC1TL = 34;
  /** RegularExpression Id. */
  int BC2F = 35;
  /** RegularExpression Id. */
  int BC2FL = 36;
  /** RegularExpression Id. */
  int BC2T = 37;
  /** RegularExpression Id. */
  int BC2TL = 38;
  /** RegularExpression Id. */
  int BEQ = 39;
  /** RegularExpression Id. */
  int BEQL = 40;
  /** RegularExpression Id. */
  int BEQZ = 41;
  /** RegularExpression Id. */
  int BEQZL = 42;
  /** RegularExpression Id. */
  int BGE = 43;
  /** RegularExpression Id. */
  int BGEL = 44;
  /** RegularExpression Id. */
  int BGEU = 45;
  /** RegularExpression Id. */
  int BGEUL = 46;
  /** RegularExpression Id. */
  int BGEZ = 47;
  /** RegularExpression Id. */
  int BGEZAL = 48;
  /** RegularExpression Id. */
  int BGEZALL = 49;
  /** RegularExpression Id. */
  int BGEZL = 50;
  /** RegularExpression Id. */
  int BGT = 51;
  /** RegularExpression Id. */
  int BGTL = 52;
  /** RegularExpression Id. */
  int BGTU = 53;
  /** RegularExpression Id. */
  int BGTUL = 54;
  /** RegularExpression Id. */
  int BGTZ = 55;
  /** RegularExpression Id. */
  int BGTZL = 56;
  /** RegularExpression Id. */
  int BLE = 57;
  /** RegularExpression Id. */
  int BLEL = 58;
  /** RegularExpression Id. */
  int BLEU = 59;
  /** RegularExpression Id. */
  int BLEUL = 60;
  /** RegularExpression Id. */
  int BLEZ = 61;
  /** RegularExpression Id. */
  int BLEZL = 62;
  /** RegularExpression Id. */
  int BLT = 63;
  /** RegularExpression Id. */
  int BLTL = 64;
  /** RegularExpression Id. */
  int BLTU = 65;
  /** RegularExpression Id. */
  int BLTUL = 66;
  /** RegularExpression Id. */
  int BLTZ = 67;
  /** RegularExpression Id. */
  int BLTZAL = 68;
  /** RegularExpression Id. */
  int BLTZALL = 69;
  /** RegularExpression Id. */
  int BLTZL = 70;
  /** RegularExpression Id. */
  int BNE = 71;
  /** RegularExpression Id. */
  int BNEL = 72;
  /** RegularExpression Id. */
  int BNEZ = 73;
  /** RegularExpression Id. */
  int BNEZL = 74;
  /** RegularExpression Id. */
  int BREAK = 75;
  /** RegularExpression Id. */
  int CACHE = 76;
  /** RegularExpression Id. */
  int CFC0 = 77;
  /** RegularExpression Id. */
  int CFC1 = 78;
  /** RegularExpression Id. */
  int CFC2 = 79;
  /** RegularExpression Id. */
  int CTC0 = 80;
  /** RegularExpression Id. */
  int CTC1 = 81;
  /** RegularExpression Id. */
  int CTC2 = 82;
  /** RegularExpression Id. */
  int DABS = 83;
  /** RegularExpression Id. */
  int DADD = 84;
  /** RegularExpression Id. */
  int DADDI = 85;
  /** RegularExpression Id. */
  int DADDIU = 86;
  /** RegularExpression Id. */
  int DADDU = 87;
  /** RegularExpression Id. */
  int DDIV = 88;
  /** RegularExpression Id. */
  int DDIVD = 89;
  /** RegularExpression Id. */
  int DDIVDU = 90;
  /** RegularExpression Id. */
  int DDIVU = 91;
  /** RegularExpression Id. */
  int DIV = 92;
  /** RegularExpression Id. */
  int DIVD = 93;
  /** RegularExpression Id. */
  int DIVDU = 94;
  /** RegularExpression Id. */
  int DIVO = 95;
  /** RegularExpression Id. */
  int DIVOU = 96;
  /** RegularExpression Id. */
  int DIVU = 97;
  /** RegularExpression Id. */
  int DLA = 98;
  /** RegularExpression Id. */
  int DLI = 99;
  /** RegularExpression Id. */
  int DMADD16 = 100;
  /** RegularExpression Id. */
  int DMFC0 = 101;
  /** RegularExpression Id. */
  int DMFC1 = 102;
  /** RegularExpression Id. */
  int DMFC2 = 103;
  /** RegularExpression Id. */
  int DMTC0 = 104;
  /** RegularExpression Id. */
  int DMTC1 = 105;
  /** RegularExpression Id. */
  int DMTC2 = 106;
  /** RegularExpression Id. */
  int DMUL = 107;
  /** RegularExpression Id. */
  int DMULO = 108;
  /** RegularExpression Id. */
  int DMULOU = 109;
  /** RegularExpression Id. */
  int DMULT = 110;
  /** RegularExpression Id. */
  int DMULTU = 111;
  /** RegularExpression Id. */
  int DNEG = 112;
  /** RegularExpression Id. */
  int DNEGU = 113;
  /** RegularExpression Id. */
  int DREM = 114;
  /** RegularExpression Id. */
  int DREMU = 115;
  /** RegularExpression Id. */
  int DRET = 116;
  /** RegularExpression Id. */
  int DROL = 117;
  /** RegularExpression Id. */
  int DROR = 118;
  /** RegularExpression Id. */
  int DSLL = 119;
  /** RegularExpression Id. */
  int DSLLV = 120;
  /** RegularExpression Id. */
  int DSLL32 = 121;
  /** RegularExpression Id. */
  int DSRA = 122;
  /** RegularExpression Id. */
  int DSRA32 = 123;
  /** RegularExpression Id. */
  int DSRL = 124;
  /** RegularExpression Id. */
  int DSRLV = 125;
  /** RegularExpression Id. */
  int DSRL32 = 126;
  /** RegularExpression Id. */
  int DSUB = 127;
  /** RegularExpression Id. */
  int DSUBU = 128;
  /** RegularExpression Id. */
  int ERET = 129;
  /** RegularExpression Id. */
  int FFC = 130;
  /** RegularExpression Id. */
  int FFS = 131;
  /** RegularExpression Id. */
  int FLUSHD = 132;
  /** RegularExpression Id. */
  int J = 133;
  /** RegularExpression Id. */
  int JR = 134;
  /** RegularExpression Id. */
  int JAL = 135;
  /** RegularExpression Id. */
  int JALR = 136;
  /** RegularExpression Id. */
  int LA = 137;
  /** RegularExpression Id. */
  int LB = 138;
  /** RegularExpression Id. */
  int LBU = 139;
  /** RegularExpression Id. */
  int LD = 140;
  /** RegularExpression Id. */
  int LDL = 141;
  /** RegularExpression Id. */
  int LDR = 142;
  /** RegularExpression Id. */
  int LDXC1 = 143;
  /** RegularExpression Id. */
  int LH = 144;
  /** RegularExpression Id. */
  int LHU = 145;
  /** RegularExpression Id. */
  int LI = 146;
  /** RegularExpression Id. */
  int LL = 147;
  /** RegularExpression Id. */
  int LLD = 148;
  /** RegularExpression Id. */
  int LUI = 149;
  /** RegularExpression Id. */
  int LW = 150;
  /** RegularExpression Id. */
  int LWC1 = 151;
  /** RegularExpression Id. */
  int LWL = 152;
  /** RegularExpression Id. */
  int LWR = 153;
  /** RegularExpression Id. */
  int LWU = 154;
  /** RegularExpression Id. */
  int LWXC1 = 155;
  /** RegularExpression Id. */
  int MADD = 156;
  /** RegularExpression Id. */
  int MADDU = 157;
  /** RegularExpression Id. */
  int MAD = 158;
  /** RegularExpression Id. */
  int MADU = 159;
  /** RegularExpression Id. */
  int MADD16 = 160;
  /** RegularExpression Id. */
  int MAX = 161;
  /** RegularExpression Id. */
  int MFC0 = 162;
  /** RegularExpression Id. */
  int MFC1 = 163;
  /** RegularExpression Id. */
  int MFC2 = 164;
  /** RegularExpression Id. */
  int MFHI = 165;
  /** RegularExpression Id. */
  int MFLO = 166;
  /** RegularExpression Id. */
  int MIN = 167;
  /** RegularExpression Id. */
  int MOVE = 168;
  /** RegularExpression Id. */
  int MOVF = 169;
  /** RegularExpression Id. */
  int MOVN = 170;
  /** RegularExpression Id. */
  int MOVT = 171;
  /** RegularExpression Id. */
  int MOVZ = 172;
  /** RegularExpression Id. */
  int MSUB = 173;
  /** RegularExpression Id. */
  int MSUBU = 174;
  /** RegularExpression Id. */
  int MTC0 = 175;
  /** RegularExpression Id. */
  int MTC1 = 176;
  /** RegularExpression Id. */
  int MTC2 = 177;
  /** RegularExpression Id. */
  int MTHI = 178;
  /** RegularExpression Id. */
  int MTLO = 179;
  /** RegularExpression Id. */
  int MUL = 180;
  /** RegularExpression Id. */
  int MULU = 181;
  /** RegularExpression Id. */
  int MULO = 182;
  /** RegularExpression Id. */
  int MULOU = 183;
  /** RegularExpression Id. */
  int MULT = 184;
  /** RegularExpression Id. */
  int MULTU = 185;
  /** RegularExpression Id. */
  int NEG = 186;
  /** RegularExpression Id. */
  int NEGU = 187;
  /** RegularExpression Id. */
  int NOP = 188;
  /** RegularExpression Id. */
  int NOR = 189;
  /** RegularExpression Id. */
  int NOT = 190;
  /** RegularExpression Id. */
  int OR = 191;
  /** RegularExpression Id. */
  int ORI = 192;
  /** RegularExpression Id. */
  int PREF = 193;
  /** RegularExpression Id. */
  int PREFX = 194;
  /** RegularExpression Id. */
  int R2U = 195;
  /** RegularExpression Id. */
  int RADD = 196;
  /** RegularExpression Id. */
  int REM = 197;
  /** RegularExpression Id. */
  int REMU = 198;
  /** RegularExpression Id. */
  int RFE = 199;
  /** RegularExpression Id. */
  int RMUL = 200;
  /** RegularExpression Id. */
  int ROL = 201;
  /** RegularExpression Id. */
  int ROR = 202;
  /** RegularExpression Id. */
  int RSUB = 203;
  /** RegularExpression Id. */
  int SB = 204;
  /** RegularExpression Id. */
  int SC = 205;
  /** RegularExpression Id. */
  int SCD = 206;
  /** RegularExpression Id. */
  int SD = 207;
  /** RegularExpression Id. */
  int SDBBP = 208;
  /** RegularExpression Id. */
  int SDC1 = 209;
  /** RegularExpression Id. */
  int SDL = 210;
  /** RegularExpression Id. */
  int SDR = 211;
  /** RegularExpression Id. */
  int SDXC1 = 212;
  /** RegularExpression Id. */
  int SELSL = 213;
  /** RegularExpression Id. */
  int SELSR = 214;
  /** RegularExpression Id. */
  int SEQ = 215;
  /** RegularExpression Id. */
  int SGE = 216;
  /** RegularExpression Id. */
  int SGEU = 217;
  /** RegularExpression Id. */
  int SGT = 218;
  /** RegularExpression Id. */
  int SGTU = 219;
  /** RegularExpression Id. */
  int SH = 220;
  /** RegularExpression Id. */
  int SLE = 221;
  /** RegularExpression Id. */
  int SLEU = 222;
  /** RegularExpression Id. */
  int SLL = 223;
  /** RegularExpression Id. */
  int SLLV = 224;
  /** RegularExpression Id. */
  int SLT = 225;
  /** RegularExpression Id. */
  int SLTI = 226;
  /** RegularExpression Id. */
  int SLTIU = 227;
  /** RegularExpression Id. */
  int SLTU = 228;
  /** RegularExpression Id. */
  int SNE = 229;
  /** RegularExpression Id. */
  int SRA = 230;
  /** RegularExpression Id. */
  int SRAV = 231;
  /** RegularExpression Id. */
  int SRL = 232;
  /** RegularExpression Id. */
  int SRLV = 233;
  /** RegularExpression Id. */
  int STANDBY = 234;
  /** RegularExpression Id. */
  int SUB = 235;
  /** RegularExpression Id. */
  int SUBU = 236;
  /** RegularExpression Id. */
  int SUSPEND = 237;
  /** RegularExpression Id. */
  int SW = 238;
  /** RegularExpression Id. */
  int SWC1 = 239;
  /** RegularExpression Id. */
  int SWL = 240;
  /** RegularExpression Id. */
  int SWR = 241;
  /** RegularExpression Id. */
  int SWXC1 = 242;
  /** RegularExpression Id. */
  int SYNC = 243;
  /** RegularExpression Id. */
  int SYSCALL = 244;
  /** RegularExpression Id. */
  int TEQ = 245;
  /** RegularExpression Id. */
  int TEQI = 246;
  /** RegularExpression Id. */
  int TGE = 247;
  /** RegularExpression Id. */
  int TGEI = 248;
  /** RegularExpression Id. */
  int TGEIU = 249;
  /** RegularExpression Id. */
  int TGEU = 250;
  /** RegularExpression Id. */
  int TLBP = 251;
  /** RegularExpression Id. */
  int TLBR = 252;
  /** RegularExpression Id. */
  int TLBWI = 253;
  /** RegularExpression Id. */
  int TLBWR = 254;
  /** RegularExpression Id. */
  int TLT = 255;
  /** RegularExpression Id. */
  int TLTI = 256;
  /** RegularExpression Id. */
  int TLTIU = 257;
  /** RegularExpression Id. */
  int TLTU = 258;
  /** RegularExpression Id. */
  int TNE = 259;
  /** RegularExpression Id. */
  int TNEI = 260;
  /** RegularExpression Id. */
  int U2R = 261;
  /** RegularExpression Id. */
  int ULD = 262;
  /** RegularExpression Id. */
  int ULH = 263;
  /** RegularExpression Id. */
  int ULHU = 264;
  /** RegularExpression Id. */
  int ULW = 265;
  /** RegularExpression Id. */
  int USD = 266;
  /** RegularExpression Id. */
  int USHUSW = 267;
  /** RegularExpression Id. */
  int WAITI = 268;
  /** RegularExpression Id. */
  int WB = 269;
  /** RegularExpression Id. */
  int XOR = 270;
  /** RegularExpression Id. */
  int XORI = 271;
  /** RegularExpression Id. */
  int ABS_S = 272;
  /** RegularExpression Id. */
  int ADD_S = 273;
  /** RegularExpression Id. */
  int C_EQ_S = 274;
  /** RegularExpression Id. */
  int C_F_S = 275;
  /** RegularExpression Id. */
  int C_LE_S = 276;
  /** RegularExpression Id. */
  int C_LT_S = 277;
  /** RegularExpression Id. */
  int C_NGE_S = 278;
  /** RegularExpression Id. */
  int C_NGL_S = 279;
  /** RegularExpression Id. */
  int C_NGT_S = 280;
  /** RegularExpression Id. */
  int C_OLE_S = 281;
  /** RegularExpression Id. */
  int C_OLT_S = 282;
  /** RegularExpression Id. */
  int C_SEQ_S = 283;
  /** RegularExpression Id. */
  int C_SF_S = 284;
  /** RegularExpression Id. */
  int C_UEQ_S = 285;
  /** RegularExpression Id. */
  int C_ULE_S = 286;
  /** RegularExpression Id. */
  int C_ULT_S = 287;
  /** RegularExpression Id. */
  int C_UN_S = 288;
  /** RegularExpression Id. */
  int CEIL_L_D = 289;
  /** RegularExpression Id. */
  int CEIL_L_S = 290;
  /** RegularExpression Id. */
  int CEIL_W_D = 291;
  /** RegularExpression Id. */
  int CEIL_W_S = 292;
  /** RegularExpression Id. */
  int CVT_D_L = 293;
  /** RegularExpression Id. */
  int CVT_D_S = 294;
  /** RegularExpression Id. */
  int CVT_D_W = 295;
  /** RegularExpression Id. */
  int CVT_L_D = 296;
  /** RegularExpression Id. */
  int CVT_L_S = 297;
  /** RegularExpression Id. */
  int CVT_S_D = 298;
  /** RegularExpression Id. */
  int CVT_S_L = 299;
  /** RegularExpression Id. */
  int CVT_S_W = 300;
  /** RegularExpression Id. */
  int CVT_W_D = 301;
  /** RegularExpression Id. */
  int CVT_W_S = 302;
  /** RegularExpression Id. */
  int DIV_S = 303;
  /** RegularExpression Id. */
  int FLOOR_L_D = 304;
  /** RegularExpression Id. */
  int FLOOR_L_S = 305;
  /** RegularExpression Id. */
  int FLOOR_W_D = 306;
  /** RegularExpression Id. */
  int FLOOR_W_S = 307;
  /** RegularExpression Id. */
  int L_D = 308;
  /** RegularExpression Id. */
  int L_S = 309;
  /** RegularExpression Id. */
  int LDC1 = 310;
  /** RegularExpression Id. */
  int MADD_S = 311;
  /** RegularExpression Id. */
  int MOV_S = 312;
  /** RegularExpression Id. */
  int MOVF_S = 313;
  /** RegularExpression Id. */
  int MOVN_S = 314;
  /** RegularExpression Id. */
  int MOVT_S = 315;
  /** RegularExpression Id. */
  int MOVZ_S = 316;
  /** RegularExpression Id. */
  int MSUB_S = 317;
  /** RegularExpression Id. */
  int MUL_S = 318;
  /** RegularExpression Id. */
  int NEG_S = 319;
  /** RegularExpression Id. */
  int NMADD_S = 320;
  /** RegularExpression Id. */
  int NMSUB_S = 321;
  /** RegularExpression Id. */
  int RECIP_S = 322;
  /** RegularExpression Id. */
  int ROUND_L_D = 323;
  /** RegularExpression Id. */
  int ROUND_L_S = 324;
  /** RegularExpression Id. */
  int ROUND_W_D = 325;
  /** RegularExpression Id. */
  int ROUND_W_S = 326;
  /** RegularExpression Id. */
  int RSQRT_S = 327;
  /** RegularExpression Id. */
  int S_D = 328;
  /** RegularExpression Id. */
  int S_S = 329;
  /** RegularExpression Id. */
  int SQRT_S = 330;
  /** RegularExpression Id. */
  int SUB_S = 331;
  /** RegularExpression Id. */
  int TRUNC_L_D = 332;
  /** RegularExpression Id. */
  int TRUNC_L_S = 333;
  /** RegularExpression Id. */
  int ASCII = 334;
  /** RegularExpression Id. */
  int ASCIIZ = 335;
  /** RegularExpression Id. */
  int SPACE = 336;
  /** RegularExpression Id. */
  int BYTE = 337;
  /** RegularExpression Id. */
  int HALF = 338;
  /** RegularExpression Id. */
  int WORD = 339;
  /** RegularExpression Id. */
  int DOUBLE = 340;
  /** RegularExpression Id. */
  int FLOAT2 = 341;
  /** RegularExpression Id. */
  int SET = 342;
  /** RegularExpression Id. */
  int VOLATILE = 343;
  /** RegularExpression Id. */
  int NOVOLATILE = 344;
  /** RegularExpression Id. */
  int REORDER = 345;
  /** RegularExpression Id. */
  int NOREORDER = 346;
  /** RegularExpression Id. */
  int NOAT = 347;
  /** RegularExpression Id. */
  int MACRO = 348;
  /** RegularExpression Id. */
  int NOMACRO = 349;
  /** RegularExpression Id. */
  int BOPT = 350;
  /** RegularExpression Id. */
  int NOBOPT = 351;
  /** RegularExpression Id. */
  int NOMOVE = 352;
  /** RegularExpression Id. */
  int TEXT = 353;
  /** RegularExpression Id. */
  int DATA = 354;
  /** RegularExpression Id. */
  int RDATA = 355;
  /** RegularExpression Id. */
  int SDATA = 356;
  /** RegularExpression Id. */
  int ALIGN = 357;
  /** RegularExpression Id. */
  int GLOBL = 358;
  /** RegularExpression Id. */
  int EXTERN = 359;
  /** RegularExpression Id. */
  int COMM = 360;
  /** RegularExpression Id. */
  int LCOMM = 361;
  /** RegularExpression Id. */
  int ENT = 362;
  /** RegularExpression Id. */
  int AENT = 363;
  /** RegularExpression Id. */
  int MASK = 364;
  /** RegularExpression Id. */
  int FMASK = 365;
  /** RegularExpression Id. */
  int FRAME = 366;
  /** RegularExpression Id. */
  int END = 367;
  /** RegularExpression Id. */
  int ALIAS = 368;
  /** RegularExpression Id. */
  int BGNB = 369;
  /** RegularExpression Id. */
  int ENDB = 370;
  /** RegularExpression Id. */
  int FILE = 371;
  /** RegularExpression Id. */
  int GALIVE = 372;
  /** RegularExpression Id. */
  int GJALDEF = 373;
  /** RegularExpression Id. */
  int GJRLIVE = 374;
  /** RegularExpression Id. */
  int LAB = 375;
  /** RegularExpression Id. */
  int LIVEREG = 376;
  /** RegularExpression Id. */
  int NOALIAS = 377;
  /** RegularExpression Id. */
  int OPTION = 378;
  /** RegularExpression Id. */
  int FLAG = 379;
  /** RegularExpression Id. */
  int VERSTAMP = 380;
  /** RegularExpression Id. */
  int VREG = 381;
  /** RegularExpression Id. */
  int ZERO = 382;
  /** RegularExpression Id. */
  int AT = 383;
  /** RegularExpression Id. */
  int V0 = 384;
  /** RegularExpression Id. */
  int V1 = 385;
  /** RegularExpression Id. */
  int A0 = 386;
  /** RegularExpression Id. */
  int A1 = 387;
  /** RegularExpression Id. */
  int A2 = 388;
  /** RegularExpression Id. */
  int A3 = 389;
  /** RegularExpression Id. */
  int T0 = 390;
  /** RegularExpression Id. */
  int T1 = 391;
  /** RegularExpression Id. */
  int T2 = 392;
  /** RegularExpression Id. */
  int T3 = 393;
  /** RegularExpression Id. */
  int T4 = 394;
  /** RegularExpression Id. */
  int T5 = 395;
  /** RegularExpression Id. */
  int T6 = 396;
  /** RegularExpression Id. */
  int T7 = 397;
  /** RegularExpression Id. */
  int S0 = 398;
  /** RegularExpression Id. */
  int S1 = 399;
  /** RegularExpression Id. */
  int S2 = 400;
  /** RegularExpression Id. */
  int S3 = 401;
  /** RegularExpression Id. */
  int S4 = 402;
  /** RegularExpression Id. */
  int S5 = 403;
  /** RegularExpression Id. */
  int S6 = 404;
  /** RegularExpression Id. */
  int S7 = 405;
  /** RegularExpression Id. */
  int T8 = 406;
  /** RegularExpression Id. */
  int T9 = 407;
  /** RegularExpression Id. */
  int K0 = 408;
  /** RegularExpression Id. */
  int K1 = 409;
  /** RegularExpression Id. */
  int GP = 410;
  /** RegularExpression Id. */
  int SP = 411;
  /** RegularExpression Id. */
  int S8 = 412;
  /** RegularExpression Id. */
  int FP = 413;
  /** RegularExpression Id. */
  int RA = 414;
  /** RegularExpression Id. */
  int DZERO = 415;
  /** RegularExpression Id. */
  int DAT = 416;
  /** RegularExpression Id. */
  int DV0 = 417;
  /** RegularExpression Id. */
  int DV1 = 418;
  /** RegularExpression Id. */
  int DA0 = 419;
  /** RegularExpression Id. */
  int DA1 = 420;
  /** RegularExpression Id. */
  int DA2 = 421;
  /** RegularExpression Id. */
  int DA3 = 422;
  /** RegularExpression Id. */
  int DT0 = 423;
  /** RegularExpression Id. */
  int DT1 = 424;
  /** RegularExpression Id. */
  int DT2 = 425;
  /** RegularExpression Id. */
  int DT3 = 426;
  /** RegularExpression Id. */
  int DT4 = 427;
  /** RegularExpression Id. */
  int DT5 = 428;
  /** RegularExpression Id. */
  int DT6 = 429;
  /** RegularExpression Id. */
  int DT7 = 430;
  /** RegularExpression Id. */
  int DS0 = 431;
  /** RegularExpression Id. */
  int DS1 = 432;
  /** RegularExpression Id. */
  int DS2 = 433;
  /** RegularExpression Id. */
  int DS3 = 434;
  /** RegularExpression Id. */
  int DS4 = 435;
  /** RegularExpression Id. */
  int DS5 = 436;
  /** RegularExpression Id. */
  int DS6 = 437;
  /** RegularExpression Id. */
  int DS7 = 438;
  /** RegularExpression Id. */
  int DT8 = 439;
  /** RegularExpression Id. */
  int DT9 = 440;
  /** RegularExpression Id. */
  int DK0 = 441;
  /** RegularExpression Id. */
  int DK1 = 442;
  /** RegularExpression Id. */
  int DGP = 443;
  /** RegularExpression Id. */
  int DSP = 444;
  /** RegularExpression Id. */
  int DS8 = 445;
  /** RegularExpression Id. */
  int DFP = 446;
  /** RegularExpression Id. */
  int DRA = 447;
  /** RegularExpression Id. */
  int DECIMAL = 448;
  /** RegularExpression Id. */
  int FLOAT = 449;
  /** RegularExpression Id. */
  int HEXADECIMAL = 450;
  /** RegularExpression Id. */
  int OCTAL = 451;
  /** RegularExpression Id. */
  int CHARACTER = 452;
  /** RegularExpression Id. */
  int STRING = 453;
  /** RegularExpression Id. */
  int DOLLAR_DECIMAL = 454;
  /** RegularExpression Id. */
  int DOLLAR_F_DECIMAL = 455;
  /** RegularExpression Id. */
  int IDENTIFIER = 456;
  /** RegularExpression Id. */
  int LETTER = 457;
  /** RegularExpression Id. */
  int DIGIT = 458;
  /** RegularExpression Id. */
  int IDENTIFIER_COLON = 459;
  /** RegularExpression Id. */
  int IDENTIFIER_EQUAL = 460;
  /** RegularExpression Id. */
  int DECIMAL_COLON = 461;
  /** RegularExpression Id. */
  int DECIMAL_B = 462;
  /** RegularExpression Id. */
  int DECIMAL_F = 463;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITE_SPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\";\"",
    "\":\"",
    "\".\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\"&\"",
    "\"^\"",
    "\"|\"",
    "\"~\"",
    "\"!\"",
    "\"abs\"",
    "\"add\"",
    "\"addciu\"",
    "\"addu\"",
    "\"and\"",
    "\"b\"",
    "\"bal\"",
    "\"bc0f\"",
    "\"bc0fl\"",
    "\"bc0t\"",
    "\"bc0tlbc1f\"",
    "\"bc1fl\"",
    "\"bc1t\"",
    "\"bc1tl\"",
    "\"bc2f\"",
    "\"bc2fl\"",
    "\"bc2t\"",
    "\"bc2tl\"",
    "\"beq\"",
    "\"beql\"",
    "\"beqz\"",
    "\"beqzl\"",
    "\"bge\"",
    "\"bgel\"",
    "\"bgeu\"",
    "\"bgeul\"",
    "\"bgez\"",
    "\"bgezal\"",
    "\"bgezall\"",
    "\"bgezl\"",
    "\"bgt\"",
    "\"bgtl\"",
    "\"bgtu\"",
    "\"bgtul\"",
    "\"bgtz\"",
    "\"bgtzl\"",
    "\"ble\"",
    "\"blel\"",
    "\"bleu\"",
    "\"bleul\"",
    "\"blez\"",
    "\"blezl\"",
    "\"blt\"",
    "\"bltl\"",
    "\"bltu\"",
    "\"bltul\"",
    "\"bltz\"",
    "\"bltzal\"",
    "\"bltzall\"",
    "\"bltzl\"",
    "\"bne\"",
    "\"bnel\"",
    "\"bnez\"",
    "\"bnezl\"",
    "\"break\"",
    "\"cache\"",
    "\"cfc0\"",
    "\"cfc1\"",
    "\"cfc2\"",
    "\"ctc0\"",
    "\"ctc1\"",
    "\"ctc2\"",
    "\"dabs\"",
    "\"dadd\"",
    "\"daddi\"",
    "\"daddiu\"",
    "\"daddu\"",
    "\"ddiv\"",
    "\"ddivd\"",
    "\"ddivdu\"",
    "\"ddivu\"",
    "\"div\"",
    "\"divd\"",
    "\"divdu\"",
    "\"divo\"",
    "\"divou\"",
    "\"divu\"",
    "\"dla\"",
    "\"dli\"",
    "\"dmadd16\"",
    "\"dmfc0\"",
    "\"dmfc1\"",
    "\"dmfc2\"",
    "\"dmtc0\"",
    "\"dmtc1\"",
    "\"dmtc2\"",
    "\"dmul\"",
    "\"dmulo\"",
    "\"dmulou\"",
    "\"dmult\"",
    "\"dmultu\"",
    "\"dneg\"",
    "\"dnegu\"",
    "\"drem\"",
    "\"dremu\"",
    "\"dret\"",
    "\"drol\"",
    "\"dror\"",
    "\"dsll\"",
    "\"dsllv\"",
    "\"dsll32\"",
    "\"dsra\"",
    "\"dsra32\"",
    "\"dsrl\"",
    "\"dsrlv\"",
    "\"dsrl32\"",
    "\"dsub\"",
    "\"dsubu\"",
    "\"eret\"",
    "\"ffc\"",
    "\"ffs\"",
    "\"flushd\"",
    "\"j\"",
    "\"jr\"",
    "\"jal\"",
    "\"jalr\"",
    "\"la\"",
    "\"lb\"",
    "\"lbu\"",
    "\"ld\"",
    "\"ldl\"",
    "\"ldr\"",
    "\"ldxc1\"",
    "\"lh\"",
    "\"lhu\"",
    "\"li\"",
    "\"ll\"",
    "\"lld\"",
    "\"lui\"",
    "\"lw\"",
    "\"lwc1\"",
    "\"lwl\"",
    "\"lwr\"",
    "\"lwu\"",
    "\"lwxc1\"",
    "\"madd\"",
    "\"maddu\"",
    "\"mad\"",
    "\"madu\"",
    "\"madd16\"",
    "\"max\"",
    "\"mfc0\"",
    "\"mfc1\"",
    "\"mfc2\"",
    "\"mfhi\"",
    "\"mflo\"",
    "\"min\"",
    "\"move\"",
    "\"movf\"",
    "\"movn\"",
    "\"movt\"",
    "\"movz\"",
    "\"msub\"",
    "\"msubu\"",
    "\"mtc0\"",
    "\"mtc1\"",
    "\"mtc2\"",
    "\"mthi\"",
    "\"mtlo\"",
    "\"mul\"",
    "\"mulu\"",
    "\"mulo\"",
    "\"mulou\"",
    "\"mult\"",
    "\"multu\"",
    "\"neg\"",
    "\"negu\"",
    "\"nop\"",
    "\"nor\"",
    "\"not\"",
    "\"or\"",
    "\"ori\"",
    "\"pref\"",
    "\"prefx\"",
    "\"r2u\"",
    "\"radd\"",
    "\"rem\"",
    "\"remu\"",
    "\"rfe\"",
    "\"rmul\"",
    "\"rol\"",
    "\"ror\"",
    "\"rsub\"",
    "\"sb\"",
    "\"sc\"",
    "\"scd\"",
    "\"sd\"",
    "\"sdbbp\"",
    "\"sdc1\"",
    "\"sdl\"",
    "\"sdr\"",
    "\"sdxc1\"",
    "\"selsl\"",
    "\"selsr\"",
    "\"seq\"",
    "\"sge\"",
    "\"sgeu\"",
    "\"sgt\"",
    "\"sgtu\"",
    "\"sh\"",
    "\"sle\"",
    "\"sleu\"",
    "\"sll\"",
    "\"sllv\"",
    "\"slt\"",
    "\"slti\"",
    "\"sltiu\"",
    "\"sltu\"",
    "\"sne\"",
    "\"sra\"",
    "\"srav\"",
    "\"srl\"",
    "\"srlv\"",
    "\"standby\"",
    "\"sub\"",
    "\"subu\"",
    "\"suspend\"",
    "\"sw\"",
    "\"swc1\"",
    "\"swl\"",
    "\"swr\"",
    "\"swxc1\"",
    "\"sync\"",
    "\"syscall\"",
    "\"teq\"",
    "\"teqi\"",
    "\"tge\"",
    "\"tgei\"",
    "\"tgeiu\"",
    "\"tgeu\"",
    "\"tlbp\"",
    "\"tlbr\"",
    "\"tlbwi\"",
    "\"tlbwr\"",
    "\"tlt\"",
    "\"tlti\"",
    "\"tltiu\"",
    "\"tltu\"",
    "\"tne\"",
    "\"tnei\"",
    "\"u2r\"",
    "\"uld\"",
    "\"ulh\"",
    "\"ulhu\"",
    "\"ulw\"",
    "\"usd\"",
    "\"ushusw\"",
    "\"waiti\"",
    "\"wb\"",
    "\"xor\"",
    "\"xori\"",
    "\"abs.s\"",
    "\"add.s\"",
    "\"c.eq.s\"",
    "\"c.f.s\"",
    "\"c.le.s\"",
    "\"c.lt.s\"",
    "\"c.nge.s\"",
    "\"c.ngl.s\"",
    "\"c.ngt.s\"",
    "\"c.ole.s\"",
    "\"c.olt.s\"",
    "\"c.seq.s\"",
    "\"c.sf.s\"",
    "\"c.ueq.s\"",
    "\"c.ule.s\"",
    "\"c.ult.s\"",
    "\"c.un.s\"",
    "\"ceil.l.d\"",
    "\"ceil.l.s\"",
    "\"ceil.w.d\"",
    "\"ceil.w.s\"",
    "\"cvt.d.l\"",
    "\"cvt.d.s\"",
    "\"cvt.d.w\"",
    "\"cvt.l.d\"",
    "\"cvt.l.s\"",
    "\"cvt.s.d\"",
    "\"cvt.s.l\"",
    "\"cvt.s.w\"",
    "\"cvt.w.d\"",
    "\"cvt.w.s\"",
    "\"div.s\"",
    "\"floor.l.d\"",
    "\"floor.l.s\"",
    "\"floor.w.d\"",
    "\"floor.w.s\"",
    "\"l.d\"",
    "\"l.s\"",
    "\"ldc1\"",
    "\"madd.s\"",
    "\"mov.s\"",
    "\"movf.s\"",
    "\"movn.s\"",
    "\"movt.s\"",
    "\"movz.s\"",
    "\"msub.s\"",
    "\"mul.s\"",
    "\"neg.s\"",
    "\"nmadd.s\"",
    "\"nmsub.s\"",
    "\"recip.s\"",
    "\"round.l.d\"",
    "\"round.l.s\"",
    "\"round.w.d\"",
    "\"round.w.s\"",
    "\"rsqrt.s\"",
    "\"s.d\"",
    "\"s.s\"",
    "\"sqrt.s\"",
    "\"sub.s\"",
    "\"trunc.l.d\"",
    "\"trunc.l.s\"",
    "\".ascii\"",
    "\".asciiz\"",
    "\".space\"",
    "\".byte\"",
    "\".half\"",
    "\".word\"",
    "\".double\"",
    "\".float\"",
    "\".set\"",
    "\"volatile\"",
    "\"novolatile\"",
    "\"reorder\"",
    "\"noreorder\"",
    "\"noat\"",
    "\"macro\"",
    "\"nomacro\"",
    "\"bopt\"",
    "\"nobopt\"",
    "\"nomove\"",
    "\".text\"",
    "\".data\"",
    "\".rdata\"",
    "\".sdata\"",
    "\".align\"",
    "\".globl\"",
    "\".extern\"",
    "\".comm\"",
    "\".lcomm\"",
    "\".ent\"",
    "\".aent\"",
    "\".mask\"",
    "\".fmask\"",
    "\".frame\"",
    "\".end\"",
    "\".alias\"",
    "\".bgnb\"",
    "\".endb\"",
    "\".file\"",
    "\".galive\"",
    "\".gjaldef\"",
    "\".gjrlive\"",
    "\".lab\"",
    "\".livereg\"",
    "\".noalias\"",
    "\".option\"",
    "\"flag\"",
    "\".verstamp\"",
    "\".vreg\"",
    "\"zero\"",
    "\"at\"",
    "\"v0\"",
    "\"v1\"",
    "\"a0\"",
    "\"a1\"",
    "\"a2\"",
    "\"a3\"",
    "\"t0\"",
    "\"t1\"",
    "\"t2\"",
    "\"t3\"",
    "\"t4\"",
    "\"t5\"",
    "\"t6\"",
    "\"t7\"",
    "\"s0\"",
    "\"s1\"",
    "\"s2\"",
    "\"s3\"",
    "\"s4\"",
    "\"s5\"",
    "\"s6\"",
    "\"s7\"",
    "\"t8\"",
    "\"t9\"",
    "\"k0\"",
    "\"k1\"",
    "\"gp\"",
    "\"sp\"",
    "\"s8\"",
    "\"fp\"",
    "\"ra\"",
    "\"$zero\"",
    "\"$at\"",
    "\"$v0\"",
    "\"$v1\"",
    "\"$a0\"",
    "\"$a1\"",
    "\"$a2\"",
    "\"$a3\"",
    "\"$t0\"",
    "\"$t1\"",
    "\"$t2\"",
    "\"$t3\"",
    "\"$t4\"",
    "\"$t5\"",
    "\"$t6\"",
    "\"$t7\"",
    "\"$s0\"",
    "\"$s1\"",
    "\"$s2\"",
    "\"$s3\"",
    "\"$s4\"",
    "\"$s5\"",
    "\"$s6\"",
    "\"$s7\"",
    "\"$t8\"",
    "\"$t9\"",
    "\"$k0\"",
    "\"$k1\"",
    "\"$gp\"",
    "\"$sp\"",
    "\"$s8\"",
    "\"$fp\"",
    "\"$ra\"",
    "<DECIMAL>",
    "<FLOAT>",
    "<HEXADECIMAL>",
    "<OCTAL>",
    "<CHARACTER>",
    "<STRING>",
    "<DOLLAR_DECIMAL>",
    "<DOLLAR_F_DECIMAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<IDENTIFIER_COLON>",
    "<IDENTIFIER_EQUAL>",
    "<DECIMAL_COLON>",
    "<DECIMAL_B>",
    "<DECIMAL_F>",
  };

}
